-- Seed strategy sessions from mock data
-- All 8 sessions seeded with published = true
-- Created 2026-05-07

INSERT INTO strategy_sessions (
  slug, title, description, date, session_date, time, facilitator,
  total_seats, attendees_override, is_past, tier, topics, agenda, key_takeaways,
  replay_url, notes_url, discussion_count, published
) VALUES
-- ── Upcoming Sessions ──────────────────────────────────────────────────────────
(
  'ai-governance-faith',
  'AI Governance for Faith Organizations',
  'Explore responsible AI adoption frameworks tailored for faith-based organizations. This session covers ethical AI policies, risk management, and governance structures that align technology decisions with your mission and values.',
  'April 15, 2026',
  '2026-04-15',
  '2:00 PM EST',
  'Keith L. Odom',
  20,
  NULL,
  false,
  'executive',
  '["AI Governance","Ethics","Faith Organizations","Policy"]',
  '[{"time":"2:00 PM","title":"Welcome & Landscape Overview","description":"Current state of AI adoption in faith-based organizations."},{"time":"2:20 PM","title":"Ethical Frameworks for AI","description":"Building governance policies that align with organizational values."},{"time":"2:50 PM","title":"Risk Assessment Workshop","description":"Hands-on exercise identifying and mitigating AI risks."},{"time":"3:20 PM","title":"Implementation Roadmap","description":"Practical steps to build your AI governance structure."},{"time":"3:45 PM","title":"Q&A and Next Steps","description":"Open discussion and action planning."}]',
  '[]',
  NULL,
  NULL,
  7,
  true
),
(
  'digital-transformation-workshop',
  'Digital Transformation Roadmapping Workshop',
  'A hands-on workshop where leaders map out a 12-month digital transformation plan. You will leave with a prioritized roadmap, budget framework, and implementation timeline customized to your organization.',
  'April 29, 2026',
  '2026-04-29',
  '1:00 PM EST',
  'Keith L. Odom',
  15,
  NULL,
  false,
  'pro',
  '["Digital Transformation","Roadmapping","Budgeting","Change Management"]',
  '[{"time":"1:00 PM","title":"Assessment & Benchmarking","description":"Evaluate your current digital maturity level."},{"time":"1:25 PM","title":"Vision Setting","description":"Define your 12-month digital transformation vision."},{"time":"1:55 PM","title":"Roadmap Workshop","description":"Collaborative exercise to build your prioritized roadmap."},{"time":"2:30 PM","title":"Budget & Resource Planning","description":"Align your roadmap with realistic budgets."},{"time":"3:00 PM","title":"Wrap-up & Commitments","description":"Share plans and commit to accountability milestones."}]',
  '[]',
  NULL,
  NULL,
  4,
  true
),
(
  'cybersecurity-small-orgs',
  'Cybersecurity Strategy for Small Organizations',
  'Learn how to build a robust cybersecurity posture without enterprise-level budgets. Covers threat landscape, affordable security tools, staff training, and incident response planning for organizations with limited IT resources.',
  'May 10, 2026',
  '2026-05-10',
  '11:00 AM EST',
  'Keith L. Odom',
  25,
  NULL,
  false,
  'pro',
  '["Cybersecurity","Small Organizations","Incident Response","Training"]',
  '[{"time":"11:00 AM","title":"Threat Landscape Briefing","description":"Understanding the threats facing small organizations."},{"time":"11:20 AM","title":"Security Stack on a Budget","description":"Affordable tools and platforms for small teams."},{"time":"11:50 AM","title":"Staff Awareness Training","description":"Building a security-first culture in your organization."},{"time":"12:15 PM","title":"Incident Response Planning","description":"Creating a response plan you can actually execute."},{"time":"12:40 PM","title":"Open Discussion","description":"Peer-to-peer sharing and Q&A."}]',
  '[]',
  NULL,
  NULL,
  2,
  true
),
(
  'future-church-tech-2027',
  'The Future of Church Technology: 2027 and Beyond',
  'A forward-looking session exploring emerging technologies shaping ministry in the next 3-5 years. From AI-powered pastoral tools to immersive worship experiences, discover what is on the horizon and how to prepare your organization.',
  'May 22, 2026',
  '2026-05-22',
  '3:00 PM EST',
  'Keith L. Odom',
  30,
  NULL,
  false,
  'executive',
  '["Church Technology","Emerging Tech","AI Ministry","Innovation"]',
  '[{"time":"3:00 PM","title":"State of Church Technology","description":"Where we are and where we are headed."},{"time":"3:20 PM","title":"AI in Ministry","description":"Practical AI applications for churches and ministries."},{"time":"3:45 PM","title":"Immersive Worship Tech","description":"AR, VR, and spatial computing for worship."},{"time":"4:10 PM","title":"Data & Analytics for Growth","description":"Leveraging data to drive ministry impact."},{"time":"4:35 PM","title":"Panel Discussion","description":"Interactive panel with technology leaders."}]',
  '[]',
  NULL,
  NULL,
  11,
  true
),
-- ── Past Sessions ────────────────────────────────────────────────────────────
(
  'ai-ready-org',
  'Building an AI-Ready Organization',
  'This session equipped leaders with frameworks for preparing their organizations for AI adoption, covering culture, data readiness, and practical implementation strategies.',
  'February 20, 2026',
  '2026-02-20',
  '2:00 PM EST',
  'Keith L. Odom',
  25,
  22,
  true,
  'executive',
  '["AI Readiness","Culture","Data Strategy","Implementation"]',
  '[]',
  '["AI readiness starts with data hygiene, not technology purchases.","Organizations need a cross-functional AI steering committee.","Start with low-risk, high-visibility pilot projects to build momentum.","Staff training and change management are the biggest success factors.","Measure AI impact with mission-aligned KPIs, not just efficiency metrics."]',
  NULL,
  NULL,
  14,
  true
),
(
  'tech-governance-masterclass',
  'Technology Governance Masterclass',
  'A deep dive into building technology governance structures that ensure accountability, security, and strategic alignment across your organization.',
  'January 15, 2026',
  '2026-01-15',
  '1:00 PM EST',
  'Keith L. Odom',
  20,
  18,
  true,
  'pro',
  '["Governance","Compliance","Strategic Alignment","Accountability"]',
  '[]',
  '["Governance is not bureaucracy; it is strategic enablement.","Define clear roles: who owns technology decisions at each level.","Regular technology audits prevent shadow IT and security gaps.","Align governance policies with organizational mission and risk tolerance."]',
  NULL,
  NULL,
  9,
  true
),
(
  'ministry-digital-strategy',
  'Ministry Digital Strategy Deep Dive',
  'An interactive session exploring how ministries can develop comprehensive digital strategies that enhance outreach, engagement, and operational effectiveness.',
  'December 10, 2025',
  '2025-12-10',
  '2:00 PM EST',
  'Keith L. Odom',
  18,
  15,
  true,
  'executive',
  '["Ministry","Digital Strategy","Outreach","Engagement"]',
  '[]',
  '["Digital strategy must serve the mission, not replace personal connection.","Multichannel engagement requires consistent messaging and branding.","Analytics reveal which digital touchpoints drive the most engagement.","Invest in training staff to use digital tools effectively."]',
  NULL,
  NULL,
  12,
  true
),
(
  'executive-cyber-briefing',
  'Executive Cybersecurity Briefing',
  'A concise, executive-level briefing on the current cybersecurity threat landscape and practical steps leaders can take to protect their organizations.',
  'November 8, 2025',
  '2025-11-08',
  '11:00 AM EST',
  'Keith L. Odom',
  25,
  20,
  true,
  'pro',
  '["Cybersecurity","Executive Briefing","Threat Landscape","Risk Management"]',
  '[]',
  '["Phishing remains the number one attack vector for small organizations.","Multi-factor authentication is non-negotiable for all systems.","Cyber insurance requirements are tightening; start the process early.","Incident response plans must be tested, not just documented.","Board-level cybersecurity literacy is now a fiduciary responsibility."]',
  NULL,
  NULL,
  8,
  true
);
